### ISSUE TITLE
The Search Marks are still existed when :let @/ = ""

### ISSUE THREAD

**Issue by adoyle-h** [petertriho/nvim-scrollbar#48]
**To Reproduce**
1. `/word`
2. `:let @/ = ""` that cancel the searching
3. The Search Marks are still existed

**Expected behavior**
The Search Marks are cleaned.

**Screenshots**
<img width="52" alt="image" src="https://user-images.githubusercontent.com/1998490/167311345-4b4c810e-faba-4179-8367-26cb69c9ad59.png">

**Version Info (please complete the following information):**
 - NVIM: v0.7.0
 - nvim-scrollbar: commit 0a530f3f
 - nvim-hlslens: commit 19440941

**Comment by petertriho** [comment]
Thanks for finding this issue. That should fix this issue

**Comment by nyngwang** [comment]
@petertriho I still got the same result.

**Comment by adoyle-h** [comment]
> @adoyle-h Thanks for finding this issue. [6554628](https://github.com/petertriho/nvim-scrollbar/commit/65546285e14ff1291cd882f30a0d18701bc4d6be) should fix this issue

I removed all other plugins and only load nvim-hlslens and nvim-scrollbar. This issue still can be reproduced.

![iShot2022-05-09_14 25 34](https://user-images.githubusercontent.com/1998490/167352455-8f8eaae7-69f0-4c9a-aaae-060bad61f6bd.gif)

**Comment by petertriho** [comment]
@nyngwang Can you please try that now? You'll need to move the cursor though (Might be better to just call `require("scrollbar.handlers.search").hide_all()` if you want it to disappear instantly

@adoyle-h Can you see if that fixes your issue?

**Comment by adoyle-h** [comment]
@petertriho It fixed. Thank you so much!

**Comment by nyngwang** [comment]
Confirmed the fix too.

**Comment by petertriho** [comment]
@nyngwang do you have these mappings https://github.com/kevinhwang91/nvim-hlslens#minimal-configuration? It should be working 

```
local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
```

**Comment by nyngwang** [comment]
Could you explain the usage of `v:count1` here?
